version = 1

[*]
fit = off
n-gpu-layers = 999
sleep-idle-seconds = 300
ctx-size = 32768
temp = 0.7
top-p = 0.8
top-k = 20

[qwen-instruct]
model = /somewhere/qwen3-4b-instruct-2507-ud-q4_k_xl.gguf
;load-on-startup = 1

[qwen-instruct-fast]
model = /somewhere/qwen3-4b-instruct-2507-q4_0.gguf

[qwen-instruct-accu]
model = /somewhere/qwen3-4b-instruct-2507-q8_0.gguf
ctx-size = 20000

[qwen-reasoning]
model = /somewhere/qwen3-4b-thinking-2507-ud-q4_k_xl.gguf
temp = 0.6
top-p = 0.95

[qwen-vl-instruct]
model = /somewhere/qwen3-vl-4b-instruct-ud-q4_k_xl.gguf
mmproj = /somewhere/qwen3-vl-4b-instruct-projf16.gguf
ctx-size = 22000

[qwen-tiny]
model = /somewhere/qwen3-1.7b-ud-q4_k_xl.gguf
temp = 0.6
top-p = 0.95

[qwen-coder]
model = /somewhere/qwen2.5-coder-1.5b-q8_0.gguf
temp = 0.0