version = 1

[*]
fit = off
n-gpu-layers = 999
sleep-idle-seconds = 300
ctx-size = 32768
temp = 0.7
top-p = 0.8
top-k = 20

[default]
;load-on-startup = 1
model = /somewhere/translator/hy-mt1.5-1.8b-q8_0.gguf

[hy7b]
model = /somewhere/translator/hy-mt1.5-7b-q4_k_m.gguf
ctx-size = 20000

[gem2b]
model = /somewhere/gemma/gemma-3n-e2b-it-absolute-heresy.i1-q4_k_m.gguf
mmproj = /somewhere/vl/mmproj-gemma-3n-e4b-it-absolute-heresy-f16.gguf

[gem4b]
model = /somewhere/gemma/gemma-3n-e4b-it-absolute-heresy-q4_k_m.gguf
mmproj = /somewhere/vl/mmproj-gemma-3n-e4b-it-absolute-heresy-f16.gguf

[qwen]
model = /somewhere/qwen/qwen3-4b-instruct-2507-ud-q4_k_xl.gguf

[qwencoder]
model = /somewhere/coder/qwen2.5-coder-1.5b-q8_0.gguf
temp = 0.0

[qwenaccu]
model = /somewhere/qwen/qwen3-4b-instruct-2507-q8_0.gguf
ctx-size = 20000